theme = "jetbrains_dark"

[editor]
line-number = "relative"
mouse = false
auto-completion = true
auto-format = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"C-c" = "normal_mode"
